import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "../components/darkmode/theme-provider";
import {ModeToggle} from "@/components/darkmode/ModeToggle";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "TodoList App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
					<div className="m-6">
						<ModeToggle />
					</div>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
